### ISSUE TITLE
Can you update Requirements.txt?

### ISSUE THREAD

**Issue by Barnacules** [mAb-Engineers/Music-Assassin#1]
Can we please get an update for requirements.txt? Half the versions don't exist when you go to install them under Python 3.8 which is what this program appears to have been written to run under. There are also a lot of conflicts. I would like to have a requirements.txt file that when installed on a clean environment it has zero conflicts and zero missing packages if at all possible. I would be happy to add one myself if I can or fork with fix if this project is no longer being maintained.

**Comment by mAb-Engineers** [comment]
Thank you for your feedback. We seemed to have missed updating it. The requirements.txt has been updated. Please provide us with feedback if you run into anymore issues.

**Comment by Barnacules** [comment]
Thank you so much! I managed to get the tool working on my own through trial and error but it's nice to have the specific dependencies that are required to make it work the best 👍
